# Generated by Django 3.2.8 on 2022-09-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_usernamedisplay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsernameDisplay',
        ),
    ]
