# Generated by Django 3.2.8 on 2022-09-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_delete_usernamedisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='getAllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
