# Generated by Django 3.2.8 on 2022-09-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_getallusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getAllUsers',
        ),
    ]
