# Generated by Django 3.2.8 on 2022-08-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
